import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Movies from './movies/movies'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Movie Search Engine!
        </h1>
        <Movies/>
      </main>
   
    </div>
  )
}
